name: BuildDocset
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install Requirements
        run: pipenv install
      - id: DRFLatestRelease
        name: Get DRF Latest Release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: encode/django-rest-framework
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout DRF
        uses: actions/checkout@v3
        with:
          repository: encode/django-rest-framework
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ steps.DRFLatestRelease.outputs.release }}
          path: .build
      - name: Build Docset
        run: |
          cd .build
          # force using file urls
          echo "use_directory_urls: false" >> mkdocs.yml
          pipenv run mkdocs build --clean

