name: BuildDocset
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install Requirements
        run: pipenv install
      - id: DRFLatestRelease
        name: Get DRF Latest Release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: encode/django-rest-framework
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout DRF
        uses: actions/checkout@v3
        with:
          repository: encode/django-rest-framework
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ steps.DRFLatestRelease.outputs.release }}
          path: .build/django-rest-framework
      - name: Build Docset
        env:
          DOC_VERSION: ${{ steps.DRFLatestRelease.outputs.release }}
        working-directory: ./.build
        run: |
          DOCSET_NAME="django-rest-framework-${DOC_VERSION}.docset"
          # force using file urls
          echo "use_directory_urls: false" >> mkdocs.yml
          cd django-rest-framework && pipenv run mkdocs build --clean && cd ..
          mkdir -p ${DOCSET_NAME}/Contents/Resources/Documents
          cp -Rf django-rest-framework/site/* ${DOCSET_NAME}/Contents/Resources/Documents/

          cp -v ../Info.plist ${DOCSET_NAME}/Contents/
          pipenv run python ../drfdoc2set.py ${DOC_VERSION} && \
            tar --exclude='.DS_Store' -czf django-rest-framework.tgz ${DOCSET_NAME}
      - name: Verify Docset
        working-directory: ./.build
        run: |
          wget http://kapeli.com/feeds/zzz/docsetcontrib.tgz && \
            tar -xvzf docsetcontrib.tgz && chmod +x docsetcontrib && \
            ./docsetcontrib --verify && echo "docset is good" || echo "verify failed"; exit 1
      - uses: actions/upload-artifact@v3
        with:
         name: django-rest-framework.tgz
         path: .build/django-rest-framework.tgz

