name: BuildDocset
on:
  # push:
#     branches:
#       - '**'
#     tags-ignore:
#       - '**'
  workflow_call:
    outputs:
      run_id:
        value: ${{ github.run_id }}
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.8'
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install Requirements
        run: pipenv install
      - id: DRFLatestRelease
        name: Get DRF Latest Release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: encode/django-rest-framework
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout DRF
        uses: actions/checkout@v3
        with:
          repository: encode/django-rest-framework
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ steps.DRFLatestRelease.outputs.release }}
          path: .build/django-rest-framework
      - name: Build Docset
        working-directory: ./.build
        run: |
          DOCSET_NAME="django-rest-framework.docset"
          cd django-rest-framework
          # force using file urls
          echo "use_directory_urls: false" >> mkdocs.yml
          pipenv run mkdocs build --clean
          cd ..
          mkdir -p ${DOCSET_NAME}/Contents/Resources/Documents
          echo "${{ steps.DRFLatestRelease.outputs.release }}" > ${DOCSET_NAME}/Contents/Resources/Documents/drf-version
          cp -Rf django-rest-framework/site/* ${DOCSET_NAME}/Contents/Resources/Documents/

          cp -v ../Info.plist ${DOCSET_NAME}/Contents/
          pipenv run python ../drfdoc2set.py && \
            tar --exclude='.DS_Store' -czf django-rest-framework.tgz ${DOCSET_NAME}
      # - name: Verify Docset
      #        run: |
      #          wget http://kapeli.com/feeds/zzz/docsetcontrib.tgz && \
      #            tar -xvzf docsetcontrib.tgz
      #          ./docsetcontrib --verify && echo "docset is good" || (echo "verify failed"; exit 1)
      - uses: actions/upload-artifact@v4
        with:
         name: django-rest-framework.tgz
         path: .build/django-rest-framework.tgz

