name: BuildDocset
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install Requirements
        run: pipenv install
      - id: DRFLatestRelease
        name: Get DRF Latest Release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: encode/django-rest-framework
          excludes: prerelease, draft
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout DRF
        uses: actions/checkout@v3
        with:
          repository: encode/django-rest-framework
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ steps.DRFLatestRelease.outputs.release }}
          path: .build/django-rest-framework
      - name: Build Docset
        env:
          DOC_VERSION: ${{ steps.DRFLatestRelease.outputs.release }}
          DOCSET_NAME: "django-rest-framework-${{ steps.DRFLatestRelease.outputs.release }}.docset"
          # DOCSET_DIR: "Dash-User-Contributions/docsets/Django_REST_Framework"
          # DOCSET_VER_DIR: "${DOCSET_DIR}/versions/${{ steps.DRFLatestRelease.outputs.release }}"
        run: |
          cd .build
          # force using file urls
          echo "use_directory_urls: false" >> mkdocs.yml
          cd django-rest-framework && pipenv run mkdocs build --clean && cd ..
          mkdir -p ${DOCSET_NAME}/Contents/Resources/Documents
          cp -Rf django-rest-framework/site/* ${DOCSET_NAME}/Contents/Resources/Documents/

          cp -v ../Info.plist ${DOCSET_NAME}/Contents/
          pipenv run python ../drfdoc2set.py ${DOC_VERSION} && \
            tar --exclude='.DS_Store' -czf django-rest-framework-${DOC_VERSION}.tgz ${DOCSET_NAME} && \
            echo " done."
      - uses: actions/upload-artifact@v3
          with:
          name: django-rest-framework.tgz
          path: .build/django-rest-framework-*.tgz
          # cp -vfp django-rest-framework-${DOC_VERSION}.tgz ${DOCSET_DIR}/django-rest-framework.tgz
#           mkdir -p ${DOCSET_VER_DIR}
#           cp -vfp django-rest-framework-${DOC_VERSION}.tgz ${DOCSET_VER_DIR}/django-rest-framework.tgz

            # cd ${WORKING_DIR}/build/Dash-User-Contributions
#             if [ ! -f docsetcontrib.tgz ]; then
#               wget http://kapeli.com/feeds/zzz/docsetcontrib.tgz
#             fi
#             tar -xzf docsetcontrib.tgz && ./docsetcontrib --verify && echo "docset is good" || echo "verify failed"; exit 1

