name: BuildDocset
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
          cache: 'pipenv'
      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
      - name: Install Requirements
        run: pipenv install
      - id: DRFLatestRelease
        name: Get DRF Latest Release
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          owner: encode
          repo: django-rest-framework
          excludes: prerelease, draft
      - name: Build Docset
        run: |
          pipenv run make run version="${{ steps.DRFLatestRelease.outputs.release }}"

